### PR TITLE
Fix angular universal server side rendering issue #77

### PR DESCRIPTION
**Pull request by fadelguy**
**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
document is not defined in angular universal server side

**What is the new behavior?**
no errors.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by MatejBivr** [comment]
Hi, any updates on when this will be merged?

**Comment by zolakt** [comment]
Any updates?

**Comment by Enslev** [comment]
Has this PR been forgotten?
Any updates on if this bug will be fixed?

**Comment by worksoncloud** [comment]
SSR support was added in PR #159.

**Pull request closed without merging**
