### PR TITLE
Angular 17 migration

### PR DESCRIPTION
**Pull request by BhuiyanSaif18**
**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/moribvndvs/ng2-idle/blob/master/CONTRIBUTING.md#pr
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Other : Update deps version
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[X] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Although this PR helped us to use with standalone component, but the old NgModule approach is still available to use.

### CODE REVIEW

**Comment by moribvndvs** [comment]
Thanks @BhuiyanSaif18 for this PR.

**Review by moribvndvs — APPROVED** [review]

**Comment by HarelM** [comment]
Any chance for a migration guide from how it used to work with Module vs how to use it now?
I've having a hard time understanding this change...

**Comment by msibhuiyan** [comment]
> Any chance for a migration guide from how it used to work with Module vs how to use it now? I've having a hard time understanding this change...

Hi @HarelM, This PR added support for new service registration approach in ApplicationConfig.
Previously we used to configure our NgModule like this
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    NgIdleKeepaliveModule.forRoot() // use NgIdleModule.forRoot() if not using keepalive
   // We registered the NgIdle modules here.
  ],
  providers: [],
  bootstrap: [AppComponent]
})
```
Now in the new ApplicationConfig approach we register the NgIdle services like this & remove the  ```NgIdleKeepaliveModule.forRoot()``` from NgModules.
```
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideNgIdleKeepalive(), // use provideNgIdle() if not using keepalive
   // We are registering NgIdle services here
    provideHttpClient(withFetch())
  ]
};
```

Now this ApplicationConfig allows us to register the service at root level, we can move service registration to component level with ```provideNgIdleKeepalive()```, ```provideNgIdle()``` by using the providers array of component or route.

Please do let me know if you need more clarifications.

**Comment by HarelM** [comment]
Thanks for the info! This was very helpful.

**Comment by nabilzhafri** [comment]
I think this newly introduced ApplicationConfig setup should be mentioned in the Readme? also probably in the changelog? in the changelog, the links are attached, but its not being mentioned as part of the breaking changes.

What happened if we didnt attach the `provideNgIdle()` / `provideNgIdleKeepalive()`? it won't work properly across components?

**Pull request merged**
